apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylab1-depi-shop
  labels:
    app: depi-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: depi-shop
  template:
    metadata:
      labels:
        app: depi-shop
    spec:
      containers:
      - name: depi-shop
        image: depi-shop:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
