apiVersion: v1
kind: Service
metadata:
  name: depi-shop-service
  labels:
    app: depi-shop
spec:
  selector:
    app: depi-shop
  ports:
    - port: 80      
      targetPort: 80  
  type: LoadBalancer
