- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Create docker directory with proper permissions
    file:
      path: "{{ ansible_env.HOME }}/docker/depi-shop"
      state: directory
      mode: '0755'
    become: false

  - name: clone repository
    git:
      repo: https://github.com/eslamsadawi/mydepiproject.git
      dest: "{{ ansible_env.HOME }}/docker/depi-shop"
      clone: yes
      update: yes
    become: false

  - name: create docker image
    command: docker build -t depi-shop:latest "{{ ansible_env.HOME }}/docker/depi-shop"
    args:
      chdir: "{{ ansible_env.HOME }}/docker/depi-shop"

